# Generated by Django 5.1.6 on 2025-02-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('poder', models.TextField()),
                ('portador', models.CharField(max_length=100)),
                ('forjadoPor', models.CharField(choices=[('E', 'Elfos'), ('A', 'Anões'), ('H', 'Homens'), ('S', 'Sauron')], max_length=1)),
                ('imagem', models.URLField(max_length=2000)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
